@host=http://localhost:8080
###
# @name create_user
POST {{host}}/v1/users
Content-Type: application/json
{
  "name": "Lane"
}
{{
  $global.apikey=response.parsedBody.apikey
}}

###
# @name get_users
GET {{host}}/v1/users
Content-Type: application/json
Authorization: ApiKey {{$global.apikey}}

###
# @name create_feed
POST {{host}}/v1/feeds
Content-Type: application/json
Authorization: ApiKey {{$global.apikey}}
{
  "name": "The Boot.dev Blog",
  "url": "https://blog.boot.dev/index.xml"
}
