version: '3'

dotenv: ['.env']

tasks:
  start:
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go build
      - ./blog-aggregator -h localhost -p 8080
  
  migrate:
    cmds:
      - goose up

  sqlc:
    cmds:
      - sqlc generate