version: '3'

dotenv: ['.env']

tasks:
  build:
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go build
  start:
    sources:
      - blog-aggregator
    cmds:
      - ./blog-aggregator -h localhost -p 8080

